CREATE TABLE `internships` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `department` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `requirements` text NOT NULL,
  `duration` varchar(100) NOT NULL,
  `stipend` varchar(100) NOT NULL,
  `location` varchar(255) NOT NULL,
  `type` enum('remote','onsite','hybrid') NOT NULL,
  `application_deadline` date NOT NULL,
  `start_date` date NOT NULL,
  `skills_required` text NOT NULL,
  `task_sheet_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_active` (`is_active`),
  KEY `idx_department` (`department`),
  KEY `idx_deadline` (`application_deadline`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `internship_applications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `internship_id` int NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `university` varchar(255) NOT NULL,
  `graduation_year` year NOT NULL,
  `major` varchar(255) NOT NULL,
  `gpa` decimal(3,2) DEFAULT NULL,
  `motivation` text NOT NULL,
  `project_submission_url` varchar(500) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_application` (`email`,`internship_id`),
  KEY `idx_email` (`email`),
  KEY `idx_internship` (`internship_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `internship_applications_ibfk_1` FOREIGN KEY (`internship_id`) REFERENCES `internships` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;